2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_setup.py:_flush():76] Configure stats pid to 1937291
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_setup.py:_flush():76] Loading settings from /home/mescalin/yitao/.config/wandb/settings
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_setup.py:_flush():76] Loading settings from /home/mescalin/yitao/Documents/Code/3HP_Space/wandb/settings
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'chytorch_test.py', 'program_abspath': '/home/mescalin/yitao/Documents/Code/3HP_Space/chytorch_test.py', 'program': '/home/mescalin/yitao/Documents/Code/3HP_Space/chytorch_test.py'}
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_init.py:_log_setup():526] Logging user logs to /home/mescalin/yitao/Documents/Code/3HP_Space/wandb/run-20240925_163555-603b5hdc/logs/debug.log
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_init.py:_log_setup():527] Logging internal logs to /home/mescalin/yitao/Documents/Code/3HP_Space/wandb/run-20240925_163555-603b5hdc/logs/debug-internal.log
2024-09-25 16:35:55,206 INFO    MainThread:1937291 [wandb_init.py:init():566] calling init triggers
2024-09-25 16:35:55,207 INFO    MainThread:1937291 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-09-25 16:35:55,207 INFO    MainThread:1937291 [wandb_init.py:init():616] starting backend
2024-09-25 16:35:55,207 INFO    MainThread:1937291 [wandb_init.py:init():620] setting up manager
2024-09-25 16:35:55,225 INFO    MainThread:1937291 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-25 16:35:55,233 INFO    MainThread:1937291 [wandb_init.py:init():628] backend started and connected
2024-09-25 16:35:55,257 INFO    MainThread:1937291 [wandb_init.py:init():720] updated telemetry
2024-09-25 16:35:55,279 INFO    MainThread:1937291 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-09-25 16:35:55,660 ERROR   MainThread:1937291 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-09-25 16:35:55,755 ERROR   MainThread:1937291 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-09-25 16:35:56,760 WARNING MsgRouterThr:1937291 [router.py:message_loop():77] message_loop has been closed
