2024-09-27 14:38:37,371 INFO    MainThread:30887 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_setup.py:_flush():76] Configure stats pid to 30887
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_setup.py:_flush():76] Loading settings from /home/mescalin/yitao/.config/wandb/settings
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_setup.py:_flush():76] Loading settings from /home/mescalin/yitao/Documents/Code/3HP_Space/wandb/settings
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'chytorch_test.py', 'program_abspath': '/home/mescalin/yitao/Documents/Code/3HP_Space/chytorch_test.py', 'program': '/home/mescalin/yitao/Documents/Code/3HP_Space/chytorch_test.py'}
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_init.py:_log_setup():526] Logging user logs to /home/mescalin/yitao/Documents/Code/3HP_Space/wandb/run-20240927_143837-fh95aw8j/logs/debug.log
2024-09-27 14:38:37,372 INFO    MainThread:30887 [wandb_init.py:_log_setup():527] Logging internal logs to /home/mescalin/yitao/Documents/Code/3HP_Space/wandb/run-20240927_143837-fh95aw8j/logs/debug-internal.log
2024-09-27 14:38:37,373 INFO    MainThread:30887 [wandb_init.py:init():566] calling init triggers
2024-09-27 14:38:37,373 INFO    MainThread:30887 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-09-27 14:38:37,373 INFO    MainThread:30887 [wandb_init.py:init():616] starting backend
2024-09-27 14:38:37,373 INFO    MainThread:30887 [wandb_init.py:init():620] setting up manager
2024-09-27 14:38:37,385 INFO    MainThread:30887 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-27 14:38:37,386 INFO    MainThread:30887 [wandb_init.py:init():628] backend started and connected
2024-09-27 14:38:37,396 INFO    MainThread:30887 [wandb_init.py:init():720] updated telemetry
2024-09-27 14:38:37,403 INFO    MainThread:30887 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-09-27 14:38:37,764 ERROR   MainThread:30887 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-09-27 14:38:37,853 ERROR   MainThread:30887 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-09-27 14:38:38,858 WARNING MsgRouterThr:30887 [router.py:message_loop():77] message_loop has been closed
